### ISSUE TITLE
css 選擇器

### ISSUE THREAD

**Issue by Mike-Zheng** [Mike-Zheng/javascript-note#3]
# css 選擇器

## 1. 基本選擇器

- **通配符 `*`**：選擇所有元素

  ```css
  * {
    padding: 0;
    margin: 0;
  }
  ```

- **ID 選擇器 `#id`**：優先度高，設定唯一元素

  ```css
  #app {
    background-color: #333;
    color: white;
  }
  ```

- **類別選擇器 `.class`**

  ```css
  .button {
    background-color: #007bff;
    color: white;
    padding: 10px 20px;
    border-radius: 5px;
  }
  ```

- **元素選擇器 `tag`**

  ```css
  p {
    font-size: 14px;
    line-height: 1.6;
    color: #333;
  }
  ```

---

## 2. 屬性選擇器

| 選擇器           | 功能                           | 範例                                     | 說明                                                                       |
| ---------------- | ------------------------------ | ---------------------------------------- | -------------------------------------------------------------------------- |
| `[attr]`         | 含有指定屬性的元素             | `[data-title] { color: red; }`           | 選擇所有具有 `data-title` 屬性的元素。                                     |
| `[attr="val"]`   | 屬性值完全匹配                 | `[type="button"] { color: pink; }`       | 選擇所有 `type` 屬性值為 `button` 的元素。                                 |
| `[attr~="val"]`  | 屬性值中包含指定單詞           | `[class~="active"] { color: blue; }`     | 選擇 `class` 屬性中含有單詞 `active` 的元素，單詞由空白分隔。              |
| `[attr\|="val"]` | 屬性值以指定值為前綴單詞       | `[lang\|="en"] { color: orange; }`       | 選擇 `lang` 屬性值以 `en` 開頭的元素，例如 `lang="en"` 或 `lang="en-US"`。 |
| `[attr^="val"]`  | 屬性值以指定值開頭             | `[href^="https"] { color: orchid; }`     | 選擇所有 `href` 屬性值以 `https` 開頭的元素。                              |
| `[attr$="val"]`  | 屬性值以指定值結尾             | `[src$=".jpg"] { color: greenyellow; }`  | 選擇所有 `src` 屬性值以 `.jpg` 結尾的元素。                                |
| `[attr*="val"]`  | 屬性值包含指定子字串           | `[title*="important"] { color: brown; }` | 選擇所有 `title` 屬性中包含子字串 `important` 的元素。                     |
| `[attr!="val"]`  | 屬性值不等於指定值             | `[data!="hidden"] { color: purple; }`    | 選擇所有 `data` 屬性值不等於 `hidden` 的元素（部分瀏覽器可能不支持）。     |
| `[attr=value i]` | 屬性值完全匹配（不區分大小寫） | `[type="Button" i] { color: teal; }`     | 選擇所有 `type` 屬性值為 `button` 的元素，不區分大小寫。                   |
| `[attr=value s]` | 屬性值完全匹配（區分大小寫）   | `[type="Button" s] { color: gray; }`     | 選擇所有 `type` 屬性值為 `Button` 的元素，區分大小寫。                     |

---

#### `[attr]`

```html
<div data-title="example"></div>
<div data-title="test"></div>
```

```css
[data-title] {
  color: red;
}
```

> 以上選擇器會選擇所有具有 `data-title` 屬性的元素。

---

#### `[attr="val"]`

```html
<input type="button" value="Click Me" /> <input type="text" value="Type Here" />
```

```css
[type="button"] {
  background-color: pink;
}
```

> 選擇屬性 `type` 值完全匹配 `button` 的 `<input>` 元素。

---

#### `[attr~="val"]`

```html
<div class="box active highlight"></div>
<div class="box highlight"></div>
```

```css
[class~="active"] {
  border: 2px solid blue;
}
```

> 選擇 `class` 屬性值包含單詞 `active` 的元素。

---

#### `[attr|="val"]`

```html
<p lang="en">English</p>
<p lang="en-US">American English</p>
<p lang="fr">French</p>
```

```css
[lang|="en"] {
  font-style: italic;
}
```

> 選擇 `lang` 屬性值以 `en` 開頭的元素，例如 `en` 或 `en-US`。

---

#### `[attr^="val"]`

```html
<a href="https://example.com">Secure Link</a>
<a href="http://example.com">Non-secure Link</a>
```

```css
[href^="https"] {
  color: orchid;
}
```

> 選擇 `href` 屬性值以 `https` 開頭的 `<a>` 元素。

---

#### `[attr$="val"]`

```html
<img src="image.jpg" alt="Image" /> <img src="image.png" alt="Another Image" />
```

```css
[src$=".jpg"] {
  border: 2px solid greenyellow;
}
```

> 選擇 `src` 屬性值以 `.jpg` 結尾的 `<img>` 元素。

---

#### `[attr*="val"]`

```html
<div title="This is important"></div>
<div title="Just a note"></div>
```

```css
[title*="important"] {
  background-color: brown;
}
```

> 選擇 `title` 屬性值中包含 `important` 子字串的元素。

---

#### `[attr!="val"]`

```html
<div data="visible"></div>
<div data="hidden"></div>
```

```css
[data!="hidden"] {
  color: purple;
}
```

> 選擇 `data` 屬性值不等於 `hidden` 的元素。

---

#### `[attr=value i]`

```html
<input type="Button" /> <input type="button" />
```

```css
[type="Button" i] {
  color: teal;
}
```

> 選擇 `type` 屬性值為 `button` 的元素，忽略大小寫。

---

#### `[attr=value s]`

```html
<input type="Button" /> <input type="button" />
```

```css
[type="Button" s] {
  color: gray;
}
```

> 選擇 `type` 屬性值為 `Button` 的元素，區分大小寫。

---

## 3. 伪元素選擇器

| **伺元素選擇器**            | **功能**                               | **範例**                                                                    | **補充敘述**                                                            |
| --------------------------- | -------------------------------------- | --------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| `::before`                  | 在元素內容之前插入自定義內容。         | `.item::before { content: "A"; }`                                           | 用於在元素的開頭插入內容，通常與 `content` 屬性搭配使用。               |
| `::after`                   | 在元素內容之後插入自定義內容。         | `.item::after { content: "B"; }`                                            | 用於在元素的結尾插入內容，通常與 `content` 屬性搭配使用。               |
| `::first-line`              | 格式化元素的第一行文字。               | `p::first-line { font-weight: bold; }`                                      | 用於修改段落的第一行文字樣式，例如加粗或改變顏色。                      |
| `::first-letter`            | 格式化元素的第一個字母。               | `p::first-letter { font-size: 2em; color: red; }`                           | 用於突出段落的第一個字母，例如放大或改變樣式。                          |
| `::selection`               | 使用者選取文字時的樣式。               | `::selection { background-color: orange; color: white; }`                   | 用於設定使用者選取文字時的背景色或字體顏色。                            |
| `::placeholder`             | 輸入框的佔位文字樣式。                 | `input::placeholder { color: gray; font-style: italic; }`                   | 用於修改 `<input>` 或 `<textarea>` 的佔位文字樣式。                     |
| `::marker`                  | 自定義列表項的標記符號樣式。           | `li::marker { color: red; font-size: 1.5em; }`                              | 用於修改 `<li>` 項的標記符號（例如點或數字）的樣式。                    |
| `::-webkit-scrollbar`       | 客製化滾動條（僅 Webkit 支援）。       | `::-webkit-scrollbar { width: 10px; }`                                      | 設置滾動條的寬度或高度，僅適用於 Webkit 瀏覽器（例如 Chrome、Safari）。 |
| `::-webkit-scrollbar-thumb` | 客製化滾動條滑塊樣式。                 | `::-webkit-scrollbar-thumb { background-color: #888; border-radius: 5px; }` | 用於修改滾動條的滑塊（可拖動部分）的樣式。                              |
| `::-webkit-scrollbar-track` | 客製化滾動條軌道樣式。                 | `::-webkit-scrollbar-track { background: #f0f0f0; }`                        | 用於修改滾動條的軌道背景樣式。                                          |
| `::file-selector-button`    | 自定義文件選擇按鈕樣式。               | `input[type="file"]::file-selector-button { background-color: blue; }`      | 用於修改 `<input type="file">` 的文件選擇按鈕樣式（僅部分瀏覽器支持）。 |
| `::backdrop`                | 全屏模式下，背景遮罩樣式。             | `::backdrop { background-color: rgba(0, 0, 0, 0.5); }`                      | 用於修改元素進入全屏模式（例如使用 `fullscreen API`）時的背景遮罩樣式。 |
| `::cue`                     | 設置 WebVTT 的字幕樣式（HTML5 視頻）。 | `::cue { color: white; background-color: black; }`                          | 用於修改 HTML5 視頻的字幕樣式（僅部分瀏覽器支持）。                     |
| `::part(name)`              | 修改有 `part` 屬性的 Shadow DOM 元素。 | `::part(button) { background-color: green; }`                               | 用於選擇 Shadow DOM 中的元素並修改其樣式（需要 `part` 屬性）。          |
| `::slotted(selector)`       | 選擇插槽中的內容（Shadow DOM）。       | `::slotted(h1) { color: blue; }`                                            | 用於選擇插入到 Shadow DOM 中的內容，通常與 Web Components 搭配使用。    |

---

#### `::before` 和 `::after`

```html
<div class="item">Content</div>
```

```css
.item::before {
  content: "A";
}
.item::after {
  content: "B";
}
```

> 在 `.item` 元素的內容前插入 "A"，後插入 "B"。

---

#### `::first-line`

```html
<p>This is a paragraph with multiple lines.</p>
```

```css
p::first-line {
  font-weight: bold;
  color: blue;
}
```

> 格式化段落的第一行文字，設置為藍色並加粗。

---

#### `::first-letter`

```html
<p>This is a paragraph.</p>
```

```css
p::first-letter {
  font-size: 2em;
  color: red;
}
```

> 放大段落的第一個字母並設置為紅色。

---

#### `::selection`

```html
<p>Select this text to see the effect.</p>
```

```css
::selection {
  background-color: orange;
  color: white;
}
```

> 使用者選取文字時，背景設置為橙色，文字顏色設置為白色。

---

#### `::placeholder`

```html
<input type="text" placeholder="Enter your name" />
```

```css
input::placeholder {
  color: gray;
  font-style: italic;
}
```

> 修改輸入框的佔位文字樣式，設置為灰色並斜體。

---

#### `::marker`

```html
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
</ul>
```

```css
li::marker {
  color: red;
  font-size: 1.5em;
}
```

> 修改列表項的標記符號樣式，設置為紅色並放大。

---

#### `::-webkit-scrollbar`

```html
<div class="scrollable">Content</div>
```

```css
::-webkit-scrollbar {
  width: 10px;
}
::-webkit-scrollbar-thumb {
  background-color: #888;
  border-radius: 5px;
}
::-webkit-scrollbar-track {
  background-color: #f0f0f0;
}
```

> 客製化滾動條的寬度、滑塊樣式和軌道背景。

---

#### `::file-selector-button`

```html
<input type="file" />
```

```css
input[type="file"]::file-selector-button {
  background-color: blue;
  color: white;
}
```

> 修改文件選擇按鈕樣式，設置背景為藍色，文字顏色為白色。

---

#### `::backdrop`

```html
<video id="video" controls></video>
```

```css
::backdrop {
  background-color: rgba(0, 0, 0, 0.5);
}
```

> 設置全屏模式下的背景遮罩樣式。

---

#### `::cue`

```html
<video>
  <track src="subtitles.vtt" kind="subtitles" srclang="en" label="English" />
</video>
```

```css
::cue {
  color: white;
  background-color: black;
}
```

> 修改 HTML5 視頻的字幕樣式。

---

#### `::part(name)`

```html
<div part="button">Shadow DOM Button</div>
```

```css
::part(button) {
  background-color: green;
  color: white;
}
```

> 修改 Shadow DOM 中具有 `part="button"` 的元素樣式。

---

#### `::slotted(selector)`

```html
<slot name="content"></slot>
```

```css
::slotted(h1) {
  color: blue;
}
```

> 修改插入到 Shadow DOM 中的 `<h1>` 標籤樣式。

---

## 4. 伪類選擇器

包括狀態和結構選擇條件：

| 選擇器                 | 範例                    | 範例描述                                                | 範例                                                |
| ---------------------- | ----------------------- | ------------------------------------------------------- | --------------------------------------------------- |
| `:active`              | `a:active`              | 選擇活動的連結。                                        | `<a href="#">Link</a>`                              |
| `:checked`             | `input:checked`         | 選擇每個被選中的 `<input>` 元素。                       | `<input type="checkbox" checked>`                   |
| `:disabled`            | `input:disabled`        | 選擇每個被禁用的 `<input>` 元素。                       | `<input type="text" disabled>`                      |
| `:empty`               | `p:empty`               | 選擇沒有子元素的每個 `<p>` 元素。                       | `<p></p>`                                           |
| `:enabled`             | `input:enabled`         | 選擇每個已啟用的 `<input>` 元素。                       | `<input type="text">`                               |
| `:first-child`         | `p:first-child`         | 選擇作為其父的首個子元素的 `<p>` 元素。                 | `<div><p>First Child</p></div>`                     |
| `:first-of-type`       | `p:first-of-type`       | 選擇作為其父的首個 `<p>` 元素的每個 `<p>` 元素。        | `<div><p>First of Type</p><p></p></div>`            |
| `:focus`               | `input:focus`           | 選擇獲得焦點的 `<input>` 元素。                         | `<input type="text" autofocus>`                     |
| `:focus-within`        | `div:focus-within`      | 選擇包含焦點元素的父元素。                              | `<div><input type="text" autofocus></div>`          |
| `:focus-visible`       | `input:focus-visible`   | 選擇因鍵盤或其他非鼠標方式獲得焦點的元素。              | `<input type="text" autofocus>`                     |
| `:has()`               | `div:has(> p)`          | 選擇包含直接子 `<p>` 元素的 `<div>` 元素。              | `<div><p>Child</p></div>`                           |
| `:hover`               | `a:hover`               | 選擇鼠標懸停其上的連結。                                | `<a href="#">Hover Me</a>`                          |
| `:in-range`            | `input:in-range`        | 選擇具有指定範圍內的值的 `<input>` 元素。               | `<input type="number" min="1" max="10">`            |
| `:invalid`             | `input:invalid`         | 選擇所有有無效值的 `<input>` 元素。                     | `<input type="email" value="invalid">`              |
| `:lang(language)`      | `p:lang(it)`            | 選擇每個 `lang` 屬性值以 "it" 開頭的 `<p>` 元素。       | `<p lang="it">Italian</p>`                          |
| `:last-child`          | `p:last-child`          | 選擇作為其父的最後一個子元素的 `<p>` 元素。             | `<div><p></p><p>Last Child</p></div>`               |
| `:last-of-type`        | `p:last-of-type`        | 選擇作為其父最後一個 `<p>` 元素的每個 `<p>` 元素。      | `<div><p></p><p>Last of Type</p></div>`             |
| `:link`                | `a:link`                | 選擇所有未被訪問的連結。                                | `<a href="http://example.com">Link</a>`             |
| `:not(selector)`       | `:not(p)`               | 選擇每個非 `<p>` 元素的元素。                           | `<div><span>Not a Paragraph</span></div>`           |
| `:nth-child(n)`        | `p:nth-child(2)`        | 選擇作為父的第 2 個子元素的每個 `<p>` 元素。            | `<div><p></p><p>Second Child</p></div>`             |
| `:nth-last-child(n)`   | `p:nth-last-child(2)`   | 選擇作為父的倒數第 2 個子元素的每個 `<p>` 元素。        | `<div><p>Second Last</p><p></p></div>`              |
| `:nth-last-of-type(n)` | `p:nth-last-of-type(2)` | 選擇作為父的倒數第 2 個 `<p>` 元素的每個 `<p>` 元素。   | `<div><p>Second Last of Type</p><p></p></div>`      |
| `:nth-of-type(n)`      | `p:nth-of-type(2)`      | 選擇作為父的第 2 個 `<p>` 元素的每個 `<p>` 元素。       | `<div><p></p><p>Second of Type</p></div>`           |
| `:only-of-type`        | `p:only-of-type`        | 選擇作為父唯一的 `<p>` 元素的每個 `<p>` 元素。          | `<div><p>Only of Type</p></div>`                    |
| `:only-child`          | `p:only-child`          | 選擇作為其父唯一子元素的 `<p>` 元素。                   | `<div><p>Only Child</p></div>`                      |
| `:optional`            | `input:optional`        | 選擇未帶有 `required` 屬性的 `<input>` 元素。           | `<input type="text">`                               |
| `:out-of-range`        | `input:out-of-range`    | 選擇值在指定範圍之外的 `<input>` 元素。                 | `<input type="number" min="1" max="10" value="11">` |
| `:read-only`           | `input:read-only`       | 選擇帶有 `readonly` 屬性的 `<input>` 元素。             | `<input type="text" readonly>`                      |
| `:read-write`          | `input:read-write`      | 選擇不帶有 `readonly` 屬性的 `<input>` 元素。           | `<input type="text">`                               |
| `:required`            | `input:required`        | 選擇帶有 `required` 屬性的 `<input>` 元素。             | `<input type="text" required>`                      |
| `:root`                | `:root`                 | 選擇文件的根元素。                                      | `html`                                              |
| `:target`              | `#news:target`          | 選擇當前活動的 `#news` 元素（單擊包含該錨名稱的 URL）。 | `<div id="news">News Section</div>`                 |
| `:valid`               | `input:valid`           | 選擇所有有有效值的 `<input>` 元素。                     | `<input type="email" value="email@example.com">`    |
| `:visited`             | `a:visited`             | 選擇所有已訪問的連結。                                  | `<a href="http://visited.com">Visited Link</a>`     |
| `:is()`                | `:is(h1, h2, h3)`       | 匹配任意列出的選擇器。                                  | `<h1>Title</h1>`, `<h2>Subtitle</h2>`               |
| `:where()`             | `:where(h1, h2, h3)`    | 與 `:is()` 相似，但無優先級影響。                       | `<h1>Title</h1>`, `<h2>Subtitle</h2>`               |

## 5. 選擇器優先權計算

https://www.w3.org/TR/selectors/#specificity-rules

### **CSS 選擇器優先度計算規則**

| **優先度層級**                                        | **描述**                                                         |
| ----------------------------------------------------- | ---------------------------------------------------------------- |
| `!important`                                          | 擁有最高優先度，覆蓋所有其他樣式，包括內聯樣式和選擇器。         |
| **內聯樣式**                                          | 直接寫在 HTML 標籤中的 `style` 屬性，優先度僅次於 `!important`。 |
| **ID 選擇器 (`#id`)**                                 | 每個 `#id` 計為 `(1,0,0)`，優先度高於類別、屬性和伺類選擇器。    |
| **類別 (`.class`)、屬性 (`[attr]`)、伺類 (`:hover`)** | 每個計為 `(0,1,0)`，優先度低於 ID 選擇器。                       |
| **元素 (`tag`)、伺元素 (`::before`)**                 | 每個計為 `(0,0,1)`，優先度低於類別、屬性和伺類選擇器。           |
| **通配符 (`*`)**                                      | 優先度最低，通常用於全局重置樣式。                               |

---

### **優先度表示法**

優先度用 `(A, B, C)` 表示，其中：

- `A` 表示 ID 選擇器數量。
- `B` 表示 類別、屬性、伺類選擇器數量。
- `C` 表示 元素、伺元素選擇器數量。

---

### **CSS 選擇器優先度範例**

| **選擇器**             | **優先度表示法** | **描述**                                                                                               |
| ---------------------- | ---------------- | ------------------------------------------------------------------------------------------------------ |
| `#app`                 | `(1,0,0)`        | ID 選擇器，優先度最高，作用於 `id="app"` 的元素。                                                      |
| `ul ol li.red`         | `(0,1,3)`        | 包含一個類別選擇器 `.red` 和三個元素選擇器 `ul`, `ol`, `li`。                                          |
| `.foo :is(.bar, #baz)` | `(1,1,0)`        | `:is()` 中優先度由最高的選擇器決定，`#baz` 的 ID 優先度為 `(1,0,0)`，`.bar` 的類別優先度為 `(0,1,0)`。 |
| `[id="app"]`           | `(0,1,0)`        | 屬性選擇器，優先度與類別選擇器相同，作用於 `id="app"` 的元素。                                         |
| `div`                  | `(0,0,1)`        | 元素選擇器，優先度最低，僅作用於所有 `<div>` 元素。                                                    |
| `*`                    | `(0,0,0)`        | 通配符選擇器，優先度最低，選擇所有元素。                                                               |
| `:where(.a, .b)`       | `(0,0,0)`        | `:where()` 選擇器的優先度始終為零，不影響其他選擇器的優先度計算。                                      |

---

### **特殊規則**

1. **`:is()` 與 `:where()`**

   - `:is()` 的優先度由內部最高的選擇器決定。例如 `:is(.class, #id)` 的優先度為 `(1,1,0)`。
   - `:where()` 始終視為 `(0,0,0)`，不影響優先度計算，用於降低選擇器的優先度。

2. **`!important`**
   - 擁有最高優先度，覆蓋所有其他樣式，包括內聯樣式、ID 選擇器等。

---

### **綜合範例：選擇器優先度的計算與應用**

假設有以下 HTML 結構：

```html
<div id="app" class="foo level"></div>
```

對應的 CSS：

```css
div {
  color: black;
} /* 優先度 (0,0,1) */

.foo {
  color: blue;
} /* 優先度 (0,1,0) */

#app {
  color: red;
} /* 優先度 (1,0,0) */

[id="app"] {
  color: white !important;
} /* 優先度 (0,1,0) 並且有 !important */
```

**最終效果：**

- 優先度最高的是 `!important`，因此該元素文字顏色為 `white`。

---

### **優先度規則總結**

1. `!important` > 內聯樣式 > ID 選擇器 > 類別/屬性/伺類選擇器 > 元素/伺元素選擇器 > 通配符。
2. `:is()` 的優先度由內部最高的選擇器決定，而 `:where()` 永遠為 `(0,0,0)`。
3. 當選擇器衝突時，優先度高者會覆蓋低者的樣式。
